name: Generate Client SDKs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use'
        required: true
        default: 'v7.1'

permissions:
  contents: write

jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: resources
            url: "https://api.ed-fi.org/${{ github.event.inputs.version }}/api/metadata/data/v3/resources/swagger.json"
            output: client/resources
          - name: descriptors
            url: "https://api.ed-fi.org/${{ github.event.inputs.version }}/api/metadata/data/v3/descriptors/swagger.json"
            output: client/descriptors

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenAPI Generator
      run: |
        wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.1/openapi-generator-cli-5.3.1.jar -O openapi-generator-cli.jar
        alias openapi-generator-cli='java -jar $PWD/openapi-generator-cli.jar'

    - name: Fetch Swagger JSON for ${{ matrix.name }}
      run: |
        set -e
        curl -f -o swagger-${{ matrix.name }}.json ${{ matrix.url }}

    - name: Generate PHP client SDK for ${{ matrix.name }}
      run: |
        java -jar openapi-generator-cli.jar generate -i swagger-${{ matrix.name }}.json -g php -o ${{ matrix.output }} > /dev/null 2>&1

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add client &> /dev/null
        git commit -m "Generated PHP client SDKs from Swagger" &> /dev/null
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
